# Generated by Django 4.2.2 on 2023-06-24 08:28

import Exam_Project.web.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_fruit_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='image_url',
            field=models.URLField(verbose_name='image_url'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), Exam_Project.web.validators.fruit_name_consist_only_letter], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='nutrition',
            field=models.TextField(blank=True, null=True, verbose_name='nutrition'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, default=18, editable=False, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=40, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), Exam_Project.web.validators.name_start_with_a_letter], verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='image_url'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1), Exam_Project.web.validators.name_start_with_a_letter], verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='password'),
        ),
    ]
