# Generated by Django 4.2.2 on 2023-06-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_fruit_description_alter_fruit_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='image_url',
            field=models.URLField(verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True, verbose_name='age'),
        ),
    ]
