# Generated by Django 4.2.2 on 2023-06-20 12:39

import Plants.Plants_App.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), Plants.Plants_App.validators.validate_name_plant]),
        ),
    ]
