# Generated by Django 4.2.2 on 2023-06-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_album_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='image_url',
            new_name='image_ur',
        ),
    ]
