# Generated by Django 4.2.2 on 2023-06-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_image_url_album_image_ur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='image_ur',
            new_name='image_url',
        ),
    ]
